In [313]:
import pandas as pd
import numpy as np
df = pd.read_csv('Amazon.csv')

In [314]:
df.drop('OfferTypeCode', axis=1, inplace=True)

df

,DigitalOrderItemId,DeliveryPacketId,AffectedItemQuantity,TransactionAmount,BaseCurrencyCode,ClaimCode,FXTransactionAmount,FXCurrencyCode,MonetaryComponentTypeCode
0,2F3HDBD46MVRC5EBFBERNJBJ969JPSUFE6O4BQ1ICS9M0V...,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,0.78,CAD,NaN,NaN,NaN,Tax
1,2F3HDBD46MVRC5EBFBERNJBJ969JPSUFE6O4BQ1ICS9M0V...,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,5.99,CAD,NaN,NaN,NaN,Price Amount
2,K9PSQFMHLLGIU5R0A6521N6MU0VTU3MHD9IBUTUJ3BFJD7...,AV5CC9E36RDVCIEFQAF2R0A8SPPCM5FBR74KO94M37GACQ...,1,0.00,CAD,NaN,NaN,NaN,Price Amount
3,K9PSQFMHLLGIU5R0A6521N6MU0VTU3MHD9IBUTUJ3BFJD7...,AV5CC9E36RDVCIEFQAF2R0A8SPPCM5FBR74KO94M37GACQ...,1,0.00,CAD,NaN,NaN,NaN,Tax
4,8O16UD3VH2P9TEI4E5F816MJGFHF1NN6AGN9T57EEJI8II...,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,10.27,CAD,NaN,NaN,NaN,Tax
5,8O16UD3VH2P9TEI4E5F816MJGFHF1NN6AGN9T57EEJI8II...,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,79.00,CAD,NaN,NaN,NaN,Price Amount
6,KKGO95MGC0EAPTG0SRNL40LEDHDNKPVBGEA9B23J40MUDE...,3CG2FDOLLDRJL3UD4TIFNLAA7VMO36J122J2O4BMGTSJMU...,1,0.00,CAD,NaN,NaN,NaN,Tax
7,KKGO95MGC0EAPTG0SRNL40LEDHDNKPVBGEA9B23J40MUDE...,3CG2FDOLLDRJL3UD4TIFNLAA7VMO36J122J2O4BMGTSJMU...,1,0.00,CAD,NaN,NaN,NaN,Price Amount
8,S84J6TNTIEGNSPUHA1UAE3EEECQEC7028T82G7FVK58KDQ...,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,79.00,CAD,NaN,NaN,NaN,Price Amount
9,S84J6TNTIEGNSPUHA1UAE3EEECQEC7028T82G7FVK58KDQ...,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,10.27,CAD,NaN,NaN,NaN,Tax
10,73M4NI61DUUD6J761P2CME90BEVLQOLPRJ6488NC0OC68V...,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,10.27,CAD,NaN,NaN,NaN,Tax
11,73M4NI61DUUD6J761P2CME90BEVLQOLPRJ6488NC0OC68V...,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,79.00,CAD,NaN,NaN,NaN,Price Amount
12,KGLMUH0FQABQN43J1NTC1R7D9GE871PMJHU46I7N0R6R5S...,VM6P55VH5NDSLGSOF2656UUVPV7I6EOHV96DNTIB9QUN83...,1,0.00,CAD,NaN,NaN,NaN,Tax
13,KGLMUH0FQABQN43J1NTC1R7D9GE871PMJHU46I7N0R6R5S...,VM6P55VH5NDSLGSOF2656UUVPV7I6EOHV96DNTIB9QUN83...,1,0.00,CAD,NaN,NaN,NaN,Price Amount
14,JAULNLRV8OM2BRKCL05V1DIF4P7SCSKJP7T3HT3M2CTFK2...,O9I07DELQGF642V9RVTUB8DSC10GELE4GD8P8IIJDQJN6V...,1,0.00,CAD,NaN,NaN,NaN,Price Amount
15,JAULNLRV8OM2BRKCL05V1DIF4P7SCSKJP7T3HT3M2CTFK2...,O9I07DELQGF642V9RVTUB8DSC10GELE4GD8P8IIJDQJN6V...,1,0.00,CAD,NaN,NaN,NaN,Tax
16,KNV2K6I6MIGUGD5OJD0UDFEROFH6H97Q5EGFNNQAIH0U2P...,2LVJMVG5D069R6TE7TUGARJTUC86J8OC20VTLGA3MNBNG3...,1,0.00,CAD,NaN,NaN,NaN,Price Amount
17,KNV2K6I6MIGUGD5OJD0UDFEROFH6H97Q5EGFNNQAIH0U2P...,2LVJMVG5D069R6TE7TUGARJTUC86J8OC20VTLGA3MNBNG3...,1,0.00,CAD,NaN,NaN,NaN,Tax
18,PGBESGIEIFD5PCSOHP2HUK2V1SUA48I6J00REPQVTIN2QV...,COKNJNELTSJ8TM2BOTLH5V1JMFJUSDL58I5O7DCEDPG6BT...,1,14.95,CAD,NaN,NaN,NaN,Price Amount
19,PGBESGIEIFD5PCSOHP2HUK2V1SUA48I6J00REPQVTIN2QV...,COKNJNELTSJ8TM2BOTLH5V1JMFJUSDL58I5O7DCEDPG6BT...,1,0.00,CAD,NaN,NaN,NaN,Tax
20,4SHTPLM70CFKFBHT2B7O3L4VA20A0MCS53KTQTFBR3NJG4...,TLF21IV2IJRPIUI0CG6DC3ME51K1Q0D3GKNPJC6UQK2JRI...,1,14.95,CAD,NaN,NaN,NaN,Price Amount
21,4SHTPLM70CFKFBHT2B7O3L4VA20A0MCS53KTQTFBR3NJG4...,TLF21IV2IJRPIUI0CG6DC3ME51K1Q0D3GKNPJC6UQK2JRI...,1,0.00,CAD,NaN,NaN,NaN,Tax
22,QELOIBSBTQ8P7ESFT4MUK5Q3VLNHP8PG6B8ATLUIJG2HAH...,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,-20.99,CAD,NaN,NaN,NaN,Price Amount
23,QELOIBSBTQ8P7ESFT4MUK5Q3VLNHP8PG6B8ATLUIJG2HAH...,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,20.99,CAD,NaN,NaN,NaN,Price Amount
24,QELOIBSBTQ8P7ESFT4MUK5Q3VLNHP8PG6B8ATLUIJG2HAH...,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,0.00,CAD,NaN,NaN,NaN,Tax
25,QELOIBSBTQ8P7ESFT4MUK5Q3VLNHP8PG6B8ATLUIJG2HAH...,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,0.00,CAD,NaN,NaN,NaN,Tax
26,V7K4HIVT1LNL8M24NUQ1N8EGH0TBN7HQH1S6SCVBFE3LCR...,2IUA39LQ7ATP58NSI6V0KA23AH9EQ1MCK10T9AIFHRR1HQ...,1,0.00,CAD,NaN,NaN,NaN,Price Amount
27,V7K4HIVT1LNL8M24NUQ1N8EGH0TBN7HQH1S6SCVBFE3LCR...,2IUA39LQ7ATP58NSI6V0KA23AH9EQ1MCK10T9AIFHRR1HQ...,1,0.00,CAD,NaN,NaN,NaN,Tax

In [315]:
df.drop('FXCurrencyCode', axis=1, inplace=True)

df

,DigitalOrderItemId,DeliveryPacketId,AffectedItemQuantity,TransactionAmount,BaseCurrencyCode,ClaimCode,FXTransactionAmount,MonetaryComponentTypeCode
0,2F3HDBD46MVRC5EBFBERNJBJ969JPSUFE6O4BQ1ICS9M0V...,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,0.78,CAD,NaN,NaN,Tax
1,2F3HDBD46MVRC5EBFBERNJBJ969JPSUFE6O4BQ1ICS9M0V...,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,5.99,CAD,NaN,NaN,Price Amount
2,K9PSQFMHLLGIU5R0A6521N6MU0VTU3MHD9IBUTUJ3BFJD7...,AV5CC9E36RDVCIEFQAF2R0A8SPPCM5FBR74KO94M37GACQ...,1,0.00,CAD,NaN,NaN,Price Amount
3,K9PSQFMHLLGIU5R0A6521N6MU0VTU3MHD9IBUTUJ3BFJD7...,AV5CC9E36RDVCIEFQAF2R0A8SPPCM5FBR74KO94M37GACQ...,1,0.00,CAD,NaN,NaN,Tax
4,8O16UD3VH2P9TEI4E5F816MJGFHF1NN6AGN9T57EEJI8II...,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,10.27,CAD,NaN,NaN,Tax
5,8O16UD3VH2P9TEI4E5F816MJGFHF1NN6AGN9T57EEJI8II...,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,79.00,CAD,NaN,NaN,Price Amount
6,KKGO95MGC0EAPTG0SRNL40LEDHDNKPVBGEA9B23J40MUDE...,3CG2FDOLLDRJL3UD4TIFNLAA7VMO36J122J2O4BMGTSJMU...,1,0.00,CAD,NaN,NaN,Tax
7,KKGO95MGC0EAPTG0SRNL40LEDHDNKPVBGEA9B23J40MUDE...,3CG2FDOLLDRJL3UD4TIFNLAA7VMO36J122J2O4BMGTSJMU...,1,0.00,CAD,NaN,NaN,Price Amount
8,S84J6TNTIEGNSPUHA1UAE3EEECQEC7028T82G7FVK58KDQ...,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,79.00,CAD,NaN,NaN,Price Amount
9,S84J6TNTIEGNSPUHA1UAE3EEECQEC7028T82G7FVK58KDQ...,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,10.27,CAD,NaN,NaN,Tax
10,73M4NI61DUUD6J761P2CME90BEVLQOLPRJ6488NC0OC68V...,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,10.27,CAD,NaN,NaN,Tax
11,73M4NI61DUUD6J761P2CME90BEVLQOLPRJ6488NC0OC68V...,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,79.00,CAD,NaN,NaN,Price Amount
12,KGLMUH0FQABQN43J1NTC1R7D9GE871PMJHU46I7N0R6R5S...,VM6P55VH5NDSLGSOF2656UUVPV7I6EOHV96DNTIB9QUN83...,1,0.00,CAD,NaN,NaN,Tax
13,KGLMUH0FQABQN43J1NTC1R7D9GE871PMJHU46I7N0R6R5S...,VM6P55VH5NDSLGSOF2656UUVPV7I6EOHV96DNTIB9QUN83...,1,0.00,CAD,NaN,NaN,Price Amount
14,JAULNLRV8OM2BRKCL05V1DIF4P7SCSKJP7T3HT3M2CTFK2...,O9I07DELQGF642V9RVTUB8DSC10GELE4GD8P8IIJDQJN6V...,1,0.00,CAD,NaN,NaN,Price Amount
15,JAULNLRV8OM2BRKCL05V1DIF4P7SCSKJP7T3HT3M2CTFK2...,O9I07DELQGF642V9RVTUB8DSC10GELE4GD8P8IIJDQJN6V...,1,0.00,CAD,NaN,NaN,Tax
16,KNV2K6I6MIGUGD5OJD0UDFEROFH6H97Q5EGFNNQAIH0U2P...,2LVJMVG5D069R6TE7TUGARJTUC86J8OC20VTLGA3MNBNG3...,1,0.00,CAD,NaN,NaN,Price Amount
17,KNV2K6I6MIGUGD5OJD0UDFEROFH6H97Q5EGFNNQAIH0U2P...,2LVJMVG5D069R6TE7TUGARJTUC86J8OC20VTLGA3MNBNG3...,1,0.00,CAD,NaN,NaN,Tax
18,PGBESGIEIFD5PCSOHP2HUK2V1SUA48I6J00REPQVTIN2QV...,COKNJNELTSJ8TM2BOTLH5V1JMFJUSDL58I5O7DCEDPG6BT...,1,14.95,CAD,NaN,NaN,Price Amount
19,PGBESGIEIFD5PCSOHP2HUK2V1SUA48I6J00REPQVTIN2QV...,COKNJNELTSJ8TM2BOTLH5V1JMFJUSDL58I5O7DCEDPG6BT...,1,0.00,CAD,NaN,NaN,Tax
20,4SHTPLM70CFKFBHT2B7O3L4VA20A0MCS53KTQTFBR3NJG4...,TLF21IV2IJRPIUI0CG6DC3ME51K1Q0D3GKNPJC6UQK2JRI...,1,14.95,CAD,NaN,NaN,Price Amount
21,4SHTPLM70CFKFBHT2B7O3L4VA20A0MCS53KTQTFBR3NJG4...,TLF21IV2IJRPIUI0CG6DC3ME51K1Q0D3GKNPJC6UQK2JRI...,1,0.00,CAD,NaN,NaN,Tax
22,QELOIBSBTQ8P7ESFT4MUK5Q3VLNHP8PG6B8ATLUIJG2HAH...,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,-20.99,CAD,NaN,NaN,Price Amount
23,QELOIBSBTQ8P7ESFT4MUK5Q3VLNHP8PG6B8ATLUIJG2HAH...,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,20.99,CAD,NaN,NaN,Price Amount
24,QELOIBSBTQ8P7ESFT4MUK5Q3VLNHP8PG6B8ATLUIJG2HAH...,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,0.00,CAD,NaN,NaN,Tax
25,QELOIBSBTQ8P7ESFT4MUK5Q3VLNHP8PG6B8ATLUIJG2HAH...,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,0.00,CAD,NaN,NaN,Tax
26,V7K4HIVT1LNL8M24NUQ1N8EGH0TBN7HQH1S6SCVBFE3LCR...,2IUA39LQ7ATP58NSI6V0KA23AH9EQ1MCK10T9AIFHRR1HQ...,1,0.00,CAD,NaN,NaN,Price Amount
27,V7K4HIVT1LNL8M24NUQ1N8EGH0TBN7HQH1S6SCVBFE3LCR...,2IUA39LQ7ATP58NSI6V0KA23AH9EQ1MCK10T9AIFHRR1HQ...,1,0.00,CAD,NaN,NaN,Tax

In [316]:
#pd.pivot_table(df,index=["MonetaryComponentTypeCode","TransactionAmount"])
#df.set_index(["MonetaryComponentTypeCode", "TransactionAmount"], drop=True)
#df1 = df.dropna(subset=['TransactionAmount'])
df.drop('FXTransactionAmount', axis=1, inplace=True)

In [317]:
df.drop('DigitalOrderItemId', axis=1, inplace=True)

In [318]:
df2 = df[df.TransactionAmount != 0] # to remove the rows where transaction amount is 0.00

df2

,DeliveryPacketId,AffectedItemQuantity,TransactionAmount,BaseCurrencyCode,ClaimCode,MonetaryComponentTypeCode
0,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,0.78,CAD,NaN,Tax
1,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,5.99,CAD,NaN,Price Amount
4,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,10.27,CAD,NaN,Tax
5,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,79.00,CAD,NaN,Price Amount
8,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,79.00,CAD,NaN,Price Amount
9,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,10.27,CAD,NaN,Tax
10,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,10.27,CAD,NaN,Tax
11,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,79.00,CAD,NaN,Price Amount
18,COKNJNELTSJ8TM2BOTLH5V1JMFJUSDL58I5O7DCEDPG6BT...,1,14.95,CAD,NaN,Price Amount
20,TLF21IV2IJRPIUI0CG6DC3ME51K1Q0D3GKNPJC6UQK2JRI...,1,14.95,CAD,NaN,Price Amount
22,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,-20.99,CAD,NaN,Price Amount
23,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,20.99,CAD,NaN,Price Amount

In [319]:
# sum of transactions
df["TransactionAmount"].sum()

# I spent $304.48 from 2006 until April 28th 2021

304.48

In [320]:
# average cost of transaction
df["TransactionAmount"].mean()

10.874285714285715

In [321]:
df["TransactionAmount"].median()

0.0

In [322]:
df["TransactionAmount"].max()
# a high of $79 spent

79.0

In [323]:
df["TransactionAmount"].min()

-20.99

In [324]:
df2.drop(df2.index[-2])

,DeliveryPacketId,AffectedItemQuantity,TransactionAmount,BaseCurrencyCode,ClaimCode,MonetaryComponentTypeCode
0,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,0.78,CAD,NaN,Tax
1,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,5.99,CAD,NaN,Price Amount
4,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,10.27,CAD,NaN,Tax
5,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,79.00,CAD,NaN,Price Amount
8,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,79.00,CAD,NaN,Price Amount
9,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,10.27,CAD,NaN,Tax
10,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,10.27,CAD,NaN,Tax
11,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,79.00,CAD,NaN,Price Amount
18,COKNJNELTSJ8TM2BOTLH5V1JMFJUSDL58I5O7DCEDPG6BT...,1,14.95,CAD,NaN,Price Amount
20,TLF21IV2IJRPIUI0CG6DC3ME51K1Q0D3GKNPJC6UQK2JRI...,1,14.95,CAD,NaN,Price Amount
23,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,20.99,CAD,NaN,Price Amount

In [325]:
df2["ClaimCode"].drop

<bound method Series.drop of 0    NaN
1    NaN
4    NaN
5    NaN
8    NaN
9    NaN
10   NaN
11   NaN
18   NaN
20   NaN
22   NaN
23   NaN
Name: ClaimCode, dtype: float64>

In [326]:
df2.drop('ClaimCode', axis=1, inplace=True)

df2

/Users/arjonbedi/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,DeliveryPacketId,AffectedItemQuantity,TransactionAmount,BaseCurrencyCode,MonetaryComponentTypeCode
0,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,0.78,CAD,Tax
1,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,5.99,CAD,Price Amount
4,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,10.27,CAD,Tax
5,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,79.00,CAD,Price Amount
8,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,79.00,CAD,Price Amount
9,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,10.27,CAD,Tax
10,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,10.27,CAD,Tax
11,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,79.00,CAD,Price Amount
18,COKNJNELTSJ8TM2BOTLH5V1JMFJUSDL58I5O7DCEDPG6BT...,1,14.95,CAD,Price Amount
20,TLF21IV2IJRPIUI0CG6DC3ME51K1Q0D3GKNPJC6UQK2JRI...,1,14.95,CAD,Price Amount
22,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,-20.99,CAD,Price Amount
23,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,20.99,CAD,Price Amount

In [327]:
df2

,DeliveryPacketId,AffectedItemQuantity,TransactionAmount,BaseCurrencyCode,MonetaryComponentTypeCode
0,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,0.78,CAD,Tax
1,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,5.99,CAD,Price Amount
4,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,10.27,CAD,Tax
5,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,79.00,CAD,Price Amount
8,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,79.00,CAD,Price Amount
9,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,10.27,CAD,Tax
10,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,10.27,CAD,Tax
11,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,79.00,CAD,Price Amount
18,COKNJNELTSJ8TM2BOTLH5V1JMFJUSDL58I5O7DCEDPG6BT...,1,14.95,CAD,Price Amount
20,TLF21IV2IJRPIUI0CG6DC3ME51K1Q0D3GKNPJC6UQK2JRI...,1,14.95,CAD,Price Amount
22,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,-20.99,CAD,Price Amount
23,49DLUE7H36BITG38SIF1E7H7LC08R8UV69IMRPL8TKSCGA...,1,20.99,CAD,Price Amount

In [328]:
### To flip the rows and columns

#df2_tr = df.transpose()
#print(df2_tr)
#df2_tr

In [329]:
df2.drop(labels=[22,23], axis=0)

,DeliveryPacketId,AffectedItemQuantity,TransactionAmount,BaseCurrencyCode,MonetaryComponentTypeCode
0,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,0.78,CAD,Tax
1,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,5.99,CAD,Price Amount
4,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,10.27,CAD,Tax
5,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,79.00,CAD,Price Amount
8,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,79.00,CAD,Price Amount
9,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,10.27,CAD,Tax
10,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,10.27,CAD,Tax
11,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,79.00,CAD,Price Amount
18,COKNJNELTSJ8TM2BOTLH5V1JMFJUSDL58I5O7DCEDPG6BT...,1,14.95,CAD,Price Amount
20,TLF21IV2IJRPIUI0CG6DC3ME51K1Q0D3GKNPJC6UQK2JRI...,1,14.95,CAD,Price Amount

In [330]:
df3 = df2.sort_values('MonetaryComponentTypeCode')

In [331]:
df4 = df3.drop(labels=[22,23], axis=0)

In [332]:
df4["TOTAL"] = df4["TransactionAmount"].cumsum(axis=0)
df4

,DeliveryPacketId,AffectedItemQuantity,TransactionAmount,BaseCurrencyCode,MonetaryComponentTypeCode,TOTAL
1,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,5.99,CAD,Price Amount,5.99
5,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,79.00,CAD,Price Amount,84.99
8,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,79.00,CAD,Price Amount,163.99
11,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,79.00,CAD,Price Amount,242.99
18,COKNJNELTSJ8TM2BOTLH5V1JMFJUSDL58I5O7DCEDPG6BT...,1,14.95,CAD,Price Amount,257.94
20,TLF21IV2IJRPIUI0CG6DC3ME51K1Q0D3GKNPJC6UQK2JRI...,1,14.95,CAD,Price Amount,272.89
0,U48DD42TAIBSU7F6DNVAF5RC1D8GQGPVHD585JP599N63P...,1,0.78,CAD,Tax,273.67
4,E9A0FQG2C2EA6Q7R8NDBJ3NCOO0NMCKFQ6DKVK3F8NSQLR...,1,10.27,CAD,Tax,283.94
9,TPQLTVTSMM780PUDOJI10O4IGJFNVT7CBCTQKNA1H8MIOB...,1,10.27,CAD,Tax,294.21
10,QVC6L2UELJDT8JHMQ2UGR5OV138ISRPBH6FDHNU9053S9M...,1,10.27,CAD,Tax,304.48

In [335]:
# I have paid $304.48 to Amazon Canada since Jan 1st, 2006